# -*- coding: utf-8 -*-
"""DetectorMovimento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWzoQL2QEo8mpSOetSdfgrgTnRlmVIPs
"""

from moviepy.editor import *
from google.colab.patches import cv2_imshow
from google.colab import drive
import numpy as np 
import cv2


#drive.mount('/content/gdrive')
#clip = VideoFileClip('gdrive/My Drive/Colab Notebooks/Visão/ProjetoRoubo/test.mp4')

cap = cv2.VideoCapture('gdrive/My Drive/Colab Notebooks/Visão/ProjetoRoubo/cortado.mp4') 
fgbg = cv2.createBackgroundSubtractorMOG2() 
  
while(1): 
    ret, frame = cap.read() 
  
    fgmask = fgbg.apply(frame) 
   
    cv2_imshow(frame) 
    cv2_imshow(fgmask) 
  
      
    k = cv2.waitKey(30) & 0xff
    if k == 27: 
        break
      
  
cap.release() 
cv2.destroyAllWindows() 
#new_clip = clip.crop(x1=330,x2=790)
#new_clip.write_videofile("gdrive/My Drive/Colab Notebooks/Visão/ProjetoRoubo/cortado.mp4",fps=20)